package selfimprove

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/nicholas/ai-agent/llm"
)

// SkillGenerator uses LLM to generate skills from execution history
type SkillGenerator struct {
	router    *llm.Router
	learner   *ExperienceLearner
	projectRoot string
}

// NewSkillGenerator creates a new SkillGenerator
func NewSkillGenerator(router *llm.Router, learner *ExperienceLearner, projectRoot string) *SkillGenerator {
	return &SkillGenerator{
		router:    router,
		learner:   learner,
		projectRoot: projectRoot,
	}
}

// PatternCandidate represents a potential pattern for skill generation
type PatternCandidate struct {
	TaskPattern  string    `json:"taskPattern"`
	Tool         string    `json:"tool"`
	SuccessRate  float64   `json:"successRate"`
	UsageCount   int       `json:"usageCount"`
	LastUsed     time.Time `json:"lastUsed"`
	Examples     []string  `json:"examples"`
}

// GeneratedSkill represents a skill generated by the LLM
type GeneratedSkill struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Pattern     string   `json:"pattern"`
	HandlerCode string   `json:"handlerCode"`
	Confidence  float64  `json:"confidence"`
}

// DetectPatterns analyzes execution history to find repeated patterns
func (sg *SkillGenerator) DetectPatterns(ctx context.Context, minUsageCount int, minSuccessRate float64) ([]PatternCandidate, error) {
	experiences := sg.learner.GetRecentExperiences(1000) // Get recent history

	// Group experiences by task keywords
	patternMap := make(map[string]*PatternCandidate)

	for _, exp := range experiences {
		keywords := extractTaskKeywords(exp.Task)
		if len(keywords) == 0 {
			continue
		}

		// Use first keyword as pattern key
		patternKey := keywords[0]

		if _, ok := patternMap[patternKey]; !ok {
			patternMap[patternKey] = &PatternCandidate{
				TaskPattern:  patternKey,
				Tool:         exp.Tool,
				UsageCount:   0,
				Examples:     make([]string, 0),
			}
		}

		candidate := patternMap[patternKey]
		candidate.UsageCount++
		
		if exp.Success {
			candidate.SuccessRate += 1.0
		}
		
		if exp.Timestamp.After(candidate.LastUsed) {
			candidate.LastUsed = exp.Timestamp
		}

		// Store example (limit to 3)
		if len(candidate.Examples) < 3 {
			candidate.Examples = append(candidate.Examples, exp.Task)
		}
	}

	// Calculate success rates and filter
	candidates := make([]PatternCandidate, 0)
	for _, candidate := range patternMap {
		candidate.SuccessRate = candidate.SuccessRate / float64(candidate.UsageCount)

		// Filter by criteria
		if candidate.UsageCount >= minUsageCount && 
		   candidate.SuccessRate >= minSuccessRate {
			candidates = append(candidates, *candidate)
		}
	}

	return candidates, nil
}

// GenerateSkill generates a skill from a pattern candidate using LLM
func (sg *SkillGenerator) GenerateSkill(ctx context.Context, candidate PatternCandidate) (*GeneratedSkill, error) {
	prompt := sg.buildGenerationPrompt(candidate)

	// Use Ollama via Router
	messages := []llm.Message{
		{
			Role:    "system",
			Content: "You are an expert Go developer who creates efficient, well-tested skills. Generate valid Go code that follows best practices.",
		},
		{
			Role:    "user",
			Content: prompt,
		},
	}

	resp, err := sg.router.Chat(ctx, messages, nil)
	if err != nil {
		return nil, fmt.Errorf("LLM call failed: %w", err)
	}

	// Parse the response
	result, err := sg.parseGenerationResponse(resp.Content)
	if err != nil {
		return nil, fmt.Errorf("failed to parse LLM response: %w", err)
	}

	return result, nil
}

// buildGenerationPrompt creates the prompt for skill generation
func (sg *SkillGenerator) buildGenerationPrompt(candidate PatternCandidate) string {
	examples := strings.Join(candidate.Examples, "\n  - ")
	
	prompt := fmt.Sprintf(`I need you to generate a Go skill based on the following execution pattern.

Pattern Details:
- Task Pattern: %s
- Tool: %s
- Success Rate: %.1f%%
- Usage Count: %d
- Example Tasks:
  - %s

Your task is to:
1. Create a meaningful skill name (short, lowercase, underscores)
2. Write a brief description
3. Create a regex pattern that matches this type of task
4. Generate Go code for the skill handler

The skill handler should:
- Be in the selfimprove package
- Implement the skill logic using the pattern tool
- Handle errors gracefully
- Be efficient and well-structured

Please respond with JSON in this exact format:
{
  "name": "skill_name",
  "description": "Brief description of what the skill does",
  "pattern": "regex_pattern_to_match_tasks",
  "handlerCode": "complete Go function code",
  "confidence": 0.0-1.0
}

The handlerCode should be a complete Go function like:
func handleSkillName(ctx context.Context, input string, toolReg *tools.Registry, router *llm.Router) (string, error) {
    // Your implementation here
}`, 
		candidate.TaskPattern,
		candidate.Tool,
		candidate.SuccessRate*100,
		candidate.UsageCount,
		examples,
	)

	return prompt
}

// parseGenerationResponse parses the LLM response into GeneratedSkill
func (sg *SkillGenerator) parseGenerationResponse(content string) (*GeneratedSkill, error) {
	// Extract JSON from response (may have markdown code blocks)
	jsonStr := content
	
	// Remove markdown code blocks if present
	if strings.Contains(content, "```json") {
		start := strings.Index(content, "```json")
		if start != -1 {
			start += 7 // Skip "```json"
			end := strings.Index(content[start:], "```")
			if end != -1 {
				jsonStr = content[start : start+end]
			}
		}
	} else if strings.Contains(content, "```") {
		start := strings.Index(content, "```")
		if start != -1 {
			start += 3 // Skip "```"
			end := strings.Index(content[start:], "```")
			if end != -1 {
				jsonStr = content[start : start+end]
			}
		}
	}

	jsonStr = strings.TrimSpace(jsonStr)

	var skill GeneratedSkill
	if err := json.Unmarshal([]byte(jsonStr), &skill); err != nil {
		return nil, fmt.Errorf("JSON unmarshal failed: %w", err)
	}

	// Validate required fields
	if skill.Name == "" || skill.Pattern == "" || skill.HandlerCode == "" {
		return nil, fmt.Errorf("missing required fields in generated skill")
	}

	return &skill, nil
}

// ValidateGeneratedCode validates the generated skill code
func (sg *SkillGenerator) ValidateGeneratedCode(ctx context.Context, skill *GeneratedSkill) error {
	// For now, we'll validate by checking the code structure
	// In a full implementation, we'd write it to a temp file and run go vet/build
	
	if !strings.Contains(skill.HandlerCode, "func handle"+capitalize(skill.Name)) {
		return fmt.Errorf("handler function naming convention not followed")
	}
	
	if !strings.Contains(skill.HandlerCode, "(ctx context.Context") {
		return fmt.Errorf("handler missing context parameter")
	}

	return nil
}

// extractTaskKeywords extracts keywords from a task description
func extractTaskKeywords(task string) []string {
	// Common action verbs
	actions := map[string]bool{
		"read": true, "write": true, "create": true, "delete": true,
		"update": true, "search": true, "find": true, "list": true,
		"get": true, "set": true, "add": true, "remove": true,
		"parse": true, "convert": true, "format": true, "transform": true,
		"analyze": true, "check": true, "validate": true, "test": true,
		"build": true, "deploy": true, "install": true, "configure": true,
		"replace": true,
	}

	words := strings.Fields(task)
	keywords := make([]string, 0)

	for _, word := range words {
		lower := strings.ToLower(word)
		if actions[lower] && len(word) > 3 {
			keywords = append(keywords, lower)
		}
	}

	return keywords
}

// capitalize capitalizes the first letter of a string
func capitalize(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// RunGenerationPipeline runs the full skill generation pipeline
func (sg *SkillGenerator) RunGenerationPipeline(ctx context.Context, minUsageCount int, minSuccessRate float64) ([]*GeneratedSkill, error) {
	slog.Info("Starting skill generation pipeline",
		"minUsageCount", minUsageCount,
		"minSuccessRate", minSuccessRate,
	)

	// Step 1: Detect patterns
	candidates, err := sg.DetectPatterns(ctx, minUsageCount, minSuccessRate)
	if err != nil {
		return nil, fmt.Errorf("pattern detection failed: %w", err)
	}

	slog.Info("Detected potential patterns", "count", len(candidates))

	if len(candidates) == 0 {
		return []*GeneratedSkill{}, nil
	}

	// Step 2: Generate skills for each candidate
	generated := make([]*GeneratedSkill, 0)
	for _, candidate := range candidates {
		slog.Info("Generating skill for pattern",
			"pattern", candidate.TaskPattern,
			"tool", candidate.Tool,
		)

		skill, err := sg.GenerateSkill(ctx, candidate)
		if err != nil {
			slog.Warn("Failed to generate skill",
				"pattern", candidate.TaskPattern,
				"error", err,
			)
			continue
		}

		// Step 3: Validate generated code
		if err := sg.ValidateGeneratedCode(ctx, skill); err != nil {
			slog.Warn("Generated skill validation failed",
				"skill", skill.Name,
				"error", err,
			)
			continue
		}

		generated = append(generated, skill)
		slog.Info("Successfully generated skill",
			"name", skill.Name,
			"confidence", skill.Confidence,
		)
	}

	return generated, nil
}