package skill

import (
	"context"
	"fmt"
	"os"
	"regexp"
	"strings"
)

// GenerateSkill creates a new skill from a pattern and template.
// The template can use {0}, {1}, etc. for regex capture groups.
// For complex skills, this can generate Go code to skill/auto_<name>.go.
func (r *Registry) GenerateSkill(name, pattern, template string) error {
	re, err := regexp.Compile(pattern)
	if err != nil {
		return fmt.Errorf("invalid pattern: %w", err)
	}

	// Count capture groups in pattern
	numGroups := re.NumSubexp()

	// Create a handler that uses template substitution
	handler := func(ctx context.Context, input string) (string, error) {
		matches := re.FindStringSubmatch(input)
		if len(matches) == 0 {
			return "", fmt.Errorf("input does not match pattern")
		}

		result := template
		for i := 0; i < numGroups; i++ {
			if i+1 < len(matches) {
				placeholder := fmt.Sprintf("{%d}", i)
				result = strings.ReplaceAll(result, placeholder, matches[i+1])
			}
		}

		return result, nil
	}

	return r.Register(name, pattern, handler, "Auto-generated skill")
}

// GenerateToFile generates a new skill and saves its code to a file.
// This is useful for complex skills that need custom Go code.
func (r *Registry) GenerateToFile(name, pattern, template string) error {
	re, err := regexp.Compile(pattern)
	if err != nil {
		return fmt.Errorf("invalid pattern: %w", err)
	}

	// Generate the Go code for the skill handler
	code := generateHandlerCode(name, pattern, template, re.NumSubexp())

	// Write to auto_<name>.go
	filename := fmt.Sprintf("skill/auto_%s.go", name)
	err = os.WriteFile(filename, []byte(code), 0644)
	if err != nil {
		return fmt.Errorf("failed to write skill file: %w", err)
	}

	// Also register it in-memory for immediate use
	handler := func(ctx context.Context, input string) (string, error) {
		matches := re.FindStringSubmatch(input)
		if len(matches) == 0 {
			return "", fmt.Errorf("input does not match pattern")
		}

		result := template
		for i := 0; i < re.NumSubexp(); i++ {
			if i+1 < len(matches) {
				placeholder := fmt.Sprintf("{%d}", i)
				result = strings.ReplaceAll(result, placeholder, matches[i+1])
			}
		}

		return result, nil
	}

	return r.Register(name, pattern, handler, fmt.Sprintf("Auto-generated skill (file: %s)", filename))
}

// generateHandlerCode generates Go source code for a template-based skill handler.
func generateHandlerCode(name, pattern, template string, numGroups int) string {
	var builder strings.Builder

	builder.WriteString(fmt.Sprintf("// Code generated by skill.Registry.GenerateToFile. DO NOT EDIT.\n"))
	builder.WriteString(fmt.Sprintf("\n"))
	builder.WriteString(fmt.Sprintf("package skill\n"))
	builder.WriteString(fmt.Sprintf("\n"))
	builder.WriteString(fmt.Sprintf("import (\n"))
	builder.WriteString(fmt.Sprintf("\t\"context\"\n"))
	builder.WriteString(fmt.Sprintf("\t\"regexp\"\n"))
	builder.WriteString(fmt.Sprintf("\t\"strings\"\n"))
	builder.WriteString(fmt.Sprintf(")\n"))
	builder.WriteString(fmt.Sprintf("\n"))
	builder.WriteString(fmt.Sprintf("// handleAuto%s is an auto-generated skill handler.\n", capitalize(name)))
	builder.WriteString(fmt.Sprintf("func handleAuto%s(ctx context.Context, input string) (string, error) {\n", capitalize(name)))
	builder.WriteString(fmt.Sprintf("\t// Pattern: %s\n", pattern))
	builder.WriteString(fmt.Sprintf("\t// Template: %s\n", template))
	builder.WriteString(fmt.Sprintf("\t\n"))
	builder.WriteString(fmt.Sprintf("\tre := regexp.MustCompile(`%s`)\n", regexp.QuoteMeta(pattern)))
	builder.WriteString(fmt.Sprintf("\tmatches := re.FindStringSubmatch(input)\n"))
	builder.WriteString(fmt.Sprintf("\tif len(matches) == 0 {\n"))
	builder.WriteString(fmt.Sprintf("\t\treturn \"\", fmt.Errorf(\"input does not match pattern\")\n"))
	builder.WriteString(fmt.Sprintf("\t}\n"))
	builder.WriteString(fmt.Sprintf("\t\n"))
	builder.WriteString(fmt.Sprintf("\tresult := `%s`\n", template))
	builder.WriteString(fmt.Sprintf("\t\n"))
	builder.WriteString(fmt.Sprintf("\t// Substitute capture groups\n"))
	builder.WriteString(fmt.Sprintf("\tfor i := 0; i < %d; i++ {\n", numGroups))
	builder.WriteString(fmt.Sprintf("\t\tif i+1 < len(matches) {\n"))
	builder.WriteString(fmt.Sprintf("\t\t\tplaceholder := fmt.Sprintf(\"{%%d}\", i)\n"))
	builder.WriteString(fmt.Sprintf("\t\t\tresult = strings.ReplaceAll(result, placeholder, matches[i+1])\n"))
	builder.WriteString(fmt.Sprintf("\t\t}\n"))
	builder.WriteString(fmt.Sprintf("\t}\n"))
	builder.WriteString(fmt.Sprintf("\t\n"))
	builder.WriteString(fmt.Sprintf("\treturn result, nil\n"))
	builder.WriteString(fmt.Sprintf("}\n"))
	builder.WriteString(fmt.Sprintf("\n"))
	builder.WriteString(fmt.Sprintf("// RegisterAuto%s registers the auto-generated skill.\n", capitalize(name)))
	builder.WriteString(fmt.Sprintf("func RegisterAuto%s(r *Registry) error {\n", capitalize(name)))
	builder.WriteString(fmt.Sprintf("\treturn r.Register(\n"))
	builder.WriteString(fmt.Sprintf("\t\t\"%s\",\n", name))
	builder.WriteString(fmt.Sprintf("\t\t`%s`,\n", pattern))
	builder.WriteString(fmt.Sprintf("\t\thandleAuto%s,\n", capitalize(name)))
	builder.WriteString(fmt.Sprintf("\t\t\"Auto-generated skill\",\n"))
	builder.WriteString(fmt.Sprintf("\t)\n"))
	builder.WriteString(fmt.Sprintf("}\n"))

	return builder.String()
}

// capitalize capitalizes the first letter of a string.
func capitalize(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// Unregister removes a skill from the registry.
func (r *Registry) Unregister(name string) {
	r.mu.Lock()
	defer r.mu.Unlock()

	delete(r.skills, name)
}

// Count returns the number of registered skills.
func (r *Registry) Count() int {
	r.mu.RLock()
	defer r.mu.RUnlock()

	return len(r.skills)
}

// Describe returns the description of a skill by name.
func (r *Registry) Describe(name string) (string, bool) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	skill, ok := r.skills[name]
	if !ok {
		return "", false
	}
	return skill.Description, true
}