// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: hitl.proto

package hitlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HITLService_SubscribeHelpRequests_FullMethodName = "/kyoci.hitl.v1.HITLService/SubscribeHelpRequests"
	HITLService_SubmitHint_FullMethodName            = "/kyoci.hitl.v1.HITLService/SubmitHint"
)

// HITLServiceClient is the client API for HITLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HITLService streams HelpRequests from agents to a human operator and
// accepts HintSubmissions back. Used by the Level 4 benchmark's self-healing
// pipeline: when the orchestrator exhausts its retry budget, it emits a
// HelpRequest and blocks until the operator supplies a hint.
type HITLServiceClient interface {
	// SubscribeHelpRequests opens a server-streaming RPC. The server pushes every
	// new HelpRequest to the subscriber until the client disconnects. Only one
	// subscriber at a time is typical (one operator terminal).
	SubscribeHelpRequests(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HelpRequest], error)
	// SubmitHint delivers an operator's hint to the waiting agent goroutine.
	// Returns accepted=true if a waiter was found and notified; accepted=false
	// (with NotFound in the status) if no agent is currently waiting on task_id.
	SubmitHint(ctx context.Context, in *HintSubmission, opts ...grpc.CallOption) (*HintResponse, error)
}

type hITLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHITLServiceClient(cc grpc.ClientConnInterface) HITLServiceClient {
	return &hITLServiceClient{cc}
}

func (c *hITLServiceClient) SubscribeHelpRequests(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HelpRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HITLService_ServiceDesc.Streams[0], HITLService_SubscribeHelpRequests_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, HelpRequest]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HITLService_SubscribeHelpRequestsClient = grpc.ServerStreamingClient[HelpRequest]

func (c *hITLServiceClient) SubmitHint(ctx context.Context, in *HintSubmission, opts ...grpc.CallOption) (*HintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HintResponse)
	err := c.cc.Invoke(ctx, HITLService_SubmitHint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HITLServiceServer is the server API for HITLService service.
// All implementations must embed UnimplementedHITLServiceServer
// for forward compatibility.
//
// HITLService streams HelpRequests from agents to a human operator and
// accepts HintSubmissions back. Used by the Level 4 benchmark's self-healing
// pipeline: when the orchestrator exhausts its retry budget, it emits a
// HelpRequest and blocks until the operator supplies a hint.
type HITLServiceServer interface {
	// SubscribeHelpRequests opens a server-streaming RPC. The server pushes every
	// new HelpRequest to the subscriber until the client disconnects. Only one
	// subscriber at a time is typical (one operator terminal).
	SubscribeHelpRequests(*SubscribeRequest, grpc.ServerStreamingServer[HelpRequest]) error
	// SubmitHint delivers an operator's hint to the waiting agent goroutine.
	// Returns accepted=true if a waiter was found and notified; accepted=false
	// (with NotFound in the status) if no agent is currently waiting on task_id.
	SubmitHint(context.Context, *HintSubmission) (*HintResponse, error)
	mustEmbedUnimplementedHITLServiceServer()
}

// UnimplementedHITLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHITLServiceServer struct{}

func (UnimplementedHITLServiceServer) SubscribeHelpRequests(*SubscribeRequest, grpc.ServerStreamingServer[HelpRequest]) error {
	return status.Error(codes.Unimplemented, "method SubscribeHelpRequests not implemented")
}
func (UnimplementedHITLServiceServer) SubmitHint(context.Context, *HintSubmission) (*HintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitHint not implemented")
}
func (UnimplementedHITLServiceServer) mustEmbedUnimplementedHITLServiceServer() {}
func (UnimplementedHITLServiceServer) testEmbeddedByValue()                     {}

// UnsafeHITLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HITLServiceServer will
// result in compilation errors.
type UnsafeHITLServiceServer interface {
	mustEmbedUnimplementedHITLServiceServer()
}

func RegisterHITLServiceServer(s grpc.ServiceRegistrar, srv HITLServiceServer) {
	// If the following call panics, it indicates UnimplementedHITLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HITLService_ServiceDesc, srv)
}

func _HITLService_SubscribeHelpRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HITLServiceServer).SubscribeHelpRequests(m, &grpc.GenericServerStream[SubscribeRequest, HelpRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HITLService_SubscribeHelpRequestsServer = grpc.ServerStreamingServer[HelpRequest]

func _HITLService_SubmitHint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HintSubmission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HITLServiceServer).SubmitHint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HITLService_SubmitHint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HITLServiceServer).SubmitHint(ctx, req.(*HintSubmission))
	}
	return interceptor(ctx, in, info, handler)
}

// HITLService_ServiceDesc is the grpc.ServiceDesc for HITLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HITLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kyoci.hitl.v1.HITLService",
	HandlerType: (*HITLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitHint",
			Handler:    _HITLService_SubmitHint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeHelpRequests",
			Handler:       _HITLService_SubscribeHelpRequests_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hitl.proto",
}
