// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: hitl.proto

package hitlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscribeRequest is empty — the subscription is unfiltered. Future work may
// add filters (role, task_id pattern) but the L4 benchmark needs none.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_hitl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hitl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_hitl_proto_rawDescGZIP(), []int{0}
}

// HelpRequest is emitted by an agent that has exhausted its retry budget.
// The operator reads this on stdin (interactive mode) or just records it
// (automated mode) and responds via SubmitHint.
type HelpRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Role           string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Attempt        int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Question       string                 `protobuf:"bytes,4,opt,name=question,proto3" json:"question,omitempty"`
	LastError      string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	AttemptedFixes []string               `protobuf:"bytes,6,rep,name=attempted_fixes,json=attemptedFixes,proto3" json:"attempted_fixes,omitempty"`
	EmittedAtUnix  int64                  `protobuf:"varint,7,opt,name=emitted_at_unix,json=emittedAtUnix,proto3" json:"emitted_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HelpRequest) Reset() {
	*x = HelpRequest{}
	mi := &file_hitl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelpRequest) ProtoMessage() {}

func (x *HelpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hitl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelpRequest.ProtoReflect.Descriptor instead.
func (*HelpRequest) Descriptor() ([]byte, []int) {
	return file_hitl_proto_rawDescGZIP(), []int{1}
}

func (x *HelpRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HelpRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *HelpRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *HelpRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *HelpRequest) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *HelpRequest) GetAttemptedFixes() []string {
	if x != nil {
		return x.AttemptedFixes
	}
	return nil
}

func (x *HelpRequest) GetEmittedAtUnix() int64 {
	if x != nil {
		return x.EmittedAtUnix
	}
	return 0
}

// HintSubmission carries the operator's hint back to the waiting agent.
type HintSubmission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Hint          string                 `protobuf:"bytes,2,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HintSubmission) Reset() {
	*x = HintSubmission{}
	mi := &file_hitl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HintSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HintSubmission) ProtoMessage() {}

func (x *HintSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_hitl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HintSubmission.ProtoReflect.Descriptor instead.
func (*HintSubmission) Descriptor() ([]byte, []int) {
	return file_hitl_proto_rawDescGZIP(), []int{2}
}

func (x *HintSubmission) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HintSubmission) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

// HintResponse acknowledges the submission.
type HintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HintResponse) Reset() {
	*x = HintResponse{}
	mi := &file_hitl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HintResponse) ProtoMessage() {}

func (x *HintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hitl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HintResponse.ProtoReflect.Descriptor instead.
func (*HintResponse) Descriptor() ([]byte, []int) {
	return file_hitl_proto_rawDescGZIP(), []int{3}
}

func (x *HintResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_hitl_proto protoreflect.FileDescriptor

const file_hitl_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"hitl.proto\x12\rkyoci.hitl.v1\"\x12\n" +
	"\x10SubscribeRequest\"\xe0\x01\n" +
	"\vHelpRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12\x1a\n" +
	"\bquestion\x18\x04 \x01(\tR\bquestion\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\x12'\n" +
	"\x0fattempted_fixes\x18\x06 \x03(\tR\x0eattemptedFixes\x12&\n" +
	"\x0femitted_at_unix\x18\a \x01(\x03R\remittedAtUnix\"=\n" +
	"\x0eHintSubmission\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04hint\x18\x02 \x01(\tR\x04hint\"*\n" +
	"\fHintResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\xaf\x01\n" +
	"\vHITLService\x12V\n" +
	"\x15SubscribeHelpRequests\x12\x1f.kyoci.hitl.v1.SubscribeRequest\x1a\x1a.kyoci.hitl.v1.HelpRequest0\x01\x12H\n" +
	"\n" +
	"SubmitHint\x12\x1d.kyoci.hitl.v1.HintSubmission\x1a\x1b.kyoci.hitl.v1.HintResponseB9Z7github.com/metabbe3/Kyoci-Agent/internal/hitl/pb;hitlpbb\x06proto3"

var (
	file_hitl_proto_rawDescOnce sync.Once
	file_hitl_proto_rawDescData []byte
)

func file_hitl_proto_rawDescGZIP() []byte {
	file_hitl_proto_rawDescOnce.Do(func() {
		file_hitl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hitl_proto_rawDesc), len(file_hitl_proto_rawDesc)))
	})
	return file_hitl_proto_rawDescData
}

var file_hitl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hitl_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: kyoci.hitl.v1.SubscribeRequest
	(*HelpRequest)(nil),      // 1: kyoci.hitl.v1.HelpRequest
	(*HintSubmission)(nil),   // 2: kyoci.hitl.v1.HintSubmission
	(*HintResponse)(nil),     // 3: kyoci.hitl.v1.HintResponse
}
var file_hitl_proto_depIdxs = []int32{
	0, // 0: kyoci.hitl.v1.HITLService.SubscribeHelpRequests:input_type -> kyoci.hitl.v1.SubscribeRequest
	2, // 1: kyoci.hitl.v1.HITLService.SubmitHint:input_type -> kyoci.hitl.v1.HintSubmission
	1, // 2: kyoci.hitl.v1.HITLService.SubscribeHelpRequests:output_type -> kyoci.hitl.v1.HelpRequest
	3, // 3: kyoci.hitl.v1.HITLService.SubmitHint:output_type -> kyoci.hitl.v1.HintResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hitl_proto_init() }
func file_hitl_proto_init() {
	if File_hitl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hitl_proto_rawDesc), len(file_hitl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hitl_proto_goTypes,
		DependencyIndexes: file_hitl_proto_depIdxs,
		MessageInfos:      file_hitl_proto_msgTypes,
	}.Build()
	File_hitl_proto = out.File
	file_hitl_proto_goTypes = nil
	file_hitl_proto_depIdxs = nil
}
